language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - "pip install -U pip"
# command to install dependencies
install:
  - "pip install tox-travis tox"
# command to run tests
script: tox

notifications:
  email: false
